name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jxe-stable-diffusion-2:latest && docker push us-docker.pkg.dev/jarvice-salesengineering/images/jxe-stable-diffusion-2:latest
