name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
      -
        name: Login to repository
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_URL }}
      -
        name: Build and Push the Docker image
        run:   docker build . --file Dockerfile --tag jxe-stable-diffusion-2:latest && docker push jarvice-salesengineering/jxe-stable-diffusion-2:latest
